apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: uc11
  namespace: uc11
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: uc11
    kind: SecretStore
  target:
    name: uc11secret
    creationPolicy: Owner
  data:
  - secretKey: ENV
    remoteRef:
      key: dev/env/value #AWS Secrets Manager secret name
      property: ENV #AWS Secrets Manager secret key
