apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: uc11-pdb
  namespace: uc11
spec:
  minAvailable: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: uc11
      app.kubernetes.io/instance: uc11