---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: uc11
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: uc11
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: uc11
subjects:
- kind: ServiceAccount
  name: uc11
  namespace: uc11