apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: uc11
  namespace: uc11
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-north-1
      auth:
        jwt:
          serviceAccountRef:
            name: uc11sa