---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: uc11
  namespace: uc11
  labels:
    app.kubernetes.io/name: uc11
    app.kubernetes.io/instance: uc11
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::864723196062:role/my-role
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::864723196062:role/uc-11-role
  labels:
    app.kubernetes.io/name: uc11
    app.kubernetes.io/instance: uc11
  name: uc11sa
  namespace: uc11
